# Generated by Django 4.1 on 2023-02-23 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0005_reviews_remove_partners_deckription_services'),
    ]

    operations = [
        migrations.AlterField(
            model_name='services',
            name='price',
            field=models.JSONField(blank=True, null=True, verbose_name='Price'),
        ),
    ]
