# Generated by Django 4.1 on 2023-02-23 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0007_articles_position_partners_position_reviews_position_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='partners',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
