# Generated by Django 4.1 on 2023-02-24 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0008_partners_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='services',
            name='slug',
            field=models.SlugField(default='some-dsdsdsd', editable=False, unique=True, verbose_name='Slug'),
            preserve_default=False,
        ),
    ]
