# Generated by Django 4.1 on 2023-02-24 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0009_services_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviews',
            name='subtitle',
            field=models.JSONField(blank=True, null=True, verbose_name='Subtitle'),
        ),
    ]
