# Generated by Django 4.1 on 2023-03-13 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0010_reviews_subtitle'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='partners',
            name='position',
        ),
        migrations.AlterField(
            model_name='reviews',
            name='position',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Position'),
        ),
        migrations.AlterField(
            model_name='services',
            name='position',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Position'),
        ),
    ]
