# Generated by Django 4.1 on 2023-02-23 11:12

import admins.models
from django.db import migrations, models
import easy_thumbnails.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectApplications',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255, verbose_name='Full name')),
                ('nbm', models.CharField(max_length=255, verbose_name='Nbm')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email')),
            ],
        ),
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.JSONField(validators=[admins.models.json_field_validate], verbose_name='Title')),
                ('image_first', easy_thumbnails.fields.ThumbnailerImageField(upload_to='project_images', verbose_name='First image')),
                ('image_second', easy_thumbnails.fields.ThumbnailerImageField(upload_to='project_images', verbose_name='Second image')),
                ('link', models.URLField(blank=True, null=True, verbose_name='Link')),
                ('description', models.JSONField(blank=True, null=True, validators=[admins.models.json_field_validate], verbose_name='Descr')),
            ],
        ),
        migrations.CreateModel(
            name='ShortApplications',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255, verbose_name='Name')),
                ('nbm', models.CharField(max_length=255, verbose_name='Nbm')),
            ],
        ),
    ]
