# Generated by Django 4.1 on 2023-02-23 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectapplications',
            name='status',
            field=models.CharField(choices=[('На расмотрении', 'На расмотрении'), ('Рассмотрено', 'Рассмотрено'), ('Отклонено', 'Отклонено')], default='Рассмотрено', max_length=255, verbose_name='Status'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='projects',
            name='type',
            field=models.CharField(choices=[('Локальные проэкты', 'Локальные проэкты'), ('Международные проэкты', 'Международные проэкты')], default='Локальные проэкты', max_length=255, verbose_name='Type'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shortapplications',
            name='status',
            field=models.CharField(choices=[('На расмотрении', 'На расмотрении'), ('Рассмотрено', 'Рассмотрено'), ('Отклонено', 'Отклонено')], default='Рассмотрено', max_length=255, verbose_name='Status'),
            preserve_default=False,
        ),
    ]
