# Generated by Django 4.1 on 2023-02-23 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_projectapplications_status_projects_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectapplications',
            name='status',
            field=models.CharField(choices=[('На расмотрении', 'На расмотрении'), ('Рассмотрено', 'Рассмотрено'), ('Отклонено', 'Отклонено')], default='На расмотрении', max_length=255, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='shortapplications',
            name='status',
            field=models.CharField(choices=[('На расмотрении', 'На расмотрении'), ('Рассмотрено', 'Рассмотрено'), ('Отклонено', 'Отклонено')], default='На расмотрении', max_length=255, verbose_name='Status'),
        ),
    ]
