# Generated by Django 4.1 on 2023-02-23 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_projectapplications_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='position',
            field=models.PositiveIntegerField(default=1, verbose_name='Position'),
            preserve_default=False,
        ),
    ]
