# Generated by Django 4.1 on 2023-02-23 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0008_partners_active'),
        ('main', '0006_projects_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='serivices',
            field=models.ManyToManyField(blank=True, null=True, to='admins.services'),
        ),
    ]
