# Generated by Django 4.1 on 2023-02-23 13:22

from django.db import migrations
import easy_thumbnails.fields


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_projects_serivices'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='image_first',
            field=easy_thumbnails.fields.ThumbnailerImageField(blank=True, null=True, upload_to='project_images', verbose_name='First image'),
        ),
        migrations.AlterField(
            model_name='projects',
            name='image_second',
            field=easy_thumbnails.fields.ThumbnailerImageField(blank=True, null=True, upload_to='project_images', verbose_name='Second image'),
        ),
    ]
