# Generated by Django 4.1 on 2023-02-24 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_rename_serivices_projects_services_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shortapplications',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email'),
        ),
    ]
