# Generated by Django 4.1 on 2023-02-24 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_shortapplications_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='slug',
            field=models.SlugField(default='some-zagol-lovok', editable=False, unique=True, verbose_name='Slug'),
            preserve_default=False,
        ),
    ]
