# Generated by Django 4.1 on 2023-03-13 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_projects_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='position',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Position'),
        ),
    ]
